#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Workaround - without this line the lint-staged output has no colour highlighting (when run via husky, on windows)
exec >/dev/tty 2>&1

# lint-staged utility is used for formatting staged files, currenty not for linting...
npx lint-staged
#npm run lint